# Generated by Django 4.1.7 on 2023-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="已上传的奶山羊图像",
                        max_length=128,
                        verbose_name="图像名称",
                    ),
                ),
                (
                    "inference_time",
                    models.FloatField(editable=False, verbose_name="推理耗时(ms)"),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        editable=False, help_text="执行操作的用户id", verbose_name="用户id"
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="执行操作的用户",
                        max_length=128,
                        verbose_name="用户名称",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "操作记录",
                "verbose_name_plural": "操作记录",
            },
        ),
    ]
