"""
Django settings for segmentation_system project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

#  Django 项目配置文件，
# 用于定义项目的关键设置，包括数据库、应用注册、模板、静态文件、语言、时区以及第三方库的相关配置
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 定义了 Django 项目的根目录路径
# __file__ 是 Python 内置变量，表示当前脚本文件的路径
# resolve()将__file__ 转换为绝对路径，并解析可能存在的符号链接
# 通过两次 .parent 操作，BASE_DIR 的值是项目的根目录
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 是 Django 项目中的一个重要配置项，用于确保项目的安全性。它在 Django 的各种加密功能中起核心作用
SECRET_KEY = "django-insecure-+zorwozcx*r8bn3@v-)j@8u1e3czvjcv9l$=7)wkzyps0ft7e$"

# SECURITY WARNING: don't run with debug turned on in production!
# 打开 Django 的调试模式
DEBUG = True

# 定义允许访问该 Django 项目的主机名或 IP 地址列表。
ALLOWED_HOSTS = []


# Application definition
# 注册 Django 项目中使用的应用，包括 Django 内置应用、第三方应用和自定义应用
INSTALLED_APPS = [
    # 第三方应用
    "simpleui",  # 后台界面美化
    "import_export",    # 数据导入/导出
    # 内置应用
    "django.contrib.admin", # 管理后台
    "django.contrib.auth",# 用户认证系统
    "django.contrib.contenttypes",# 内容类型框架
    "django.contrib.sessions",  # 会话管理
    "django.contrib.messages",# 消息框架
    "django.contrib.staticfiles", # 静态文件管理
    # 自定义应用
    "instance_segmentation",  # 图像实例分割
    "feedback",  # �?题反�?
    "history",  # 历史记录管理
    # 第三方应用
    "django_cleanup.apps.CleanupConfig",  # 图像更新时自动删除旧有文件, 必须放在最后
]

# 定义 Django 项目中启用的中间件列表。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",# 安全性增强
    "django.contrib.sessions.middleware.SessionMiddleware",# 会话管理
    "django.middleware.common.CommonMiddleware", # 通用功能（如重定向）
    "django.middleware.csrf.CsrfViewMiddleware",# CSRF 防护
    "django.contrib.auth.middleware.AuthenticationMiddleware",# 用户认证
    "django.contrib.messages.middleware.MessageMiddleware", # 消息框架
    "django.middleware.clickjacking.XFrameOptionsMiddleware",# 防止点击劫持
    # 自定义中间件
    "middleware.current_user.CurrentUserMiddleware",# 用于处理当前用户相关的逻辑
]

# 指定 Django 项目的主 URL 配置文件
ROOT_URLCONF = "segmentation_system.urls"

# 定义模板引擎的配置，用于生成动态 HTML 内容
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # 指定模板�?�?
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
# 指定 Django 的 WSGI 应用对象。
WSGI_APPLICATION = "segmentation_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# 去除密码设置限制
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 系统�?言

TIME_ZONE = "Asia/Shanghai"  # 时区

USE_I18N = True

# USE_TZ = True  # 若不注释�?, timezone.now()获取的时间不�?.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 静态资�?
# 设置静态目�?
STATIC_ROOT = BASE_DIR / "static"
# 设置静态资源地址
STATICFILES_DIRS = [
    BASE_DIR / "common_static",
]
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# simpleui设置
# 首页标�??
SIMPLEUI_HOME_TITLE = "奶山羊图像实例分割系�?"
# 首页�?否显示服务器、python、django、simpleui相关信息
SIMPLEUI_HOME_INFO = False
# 首页�?否显示快速操�?
SIMPLEUI_HOME_QUICK = True
# 首页�?否显示最近动�?
SIMPLEUI_HOME_ACTION = True
# simpleui�?定义logo
SIMPLEUI_LOGO = "https://bkimg.cdn.bcebos.com/pic/f603918fa0ec08fa513dc97f71bc2a6d55fbb3fb6c92?x-bce-process=image/resize,m_lfit,w_536,limit_1"
# �?否允许simpleui进�?�使用分�?
SIMPLEUI_ANALYSIS = False
# 指定simple默�?�的主�??
SIMPLEUI_DEFAULT_THEME = "x-green.css"
# 指定simpleui�?否以脱机模式加载静态资�?
SIMPLEUI_STATIC_OFFLINE = True
# �?定义simpleui菜单
SIMPLEUI_CONFIG = {
    "system_keep": False,  # �?否在�?定义菜单的基础上保留系统模�?
    "menu_display": ["图像实例分割", "历史记录管理", "用户管理", "�?题反�?"],  # 需要和menus�?的names对应
    "menus": [
        {
            "name": "图像实例分割",
            "icon": "fa-regular fa-circle-nodes",
            "models": [
                {
                    "name": "奶山羊图�?",
                    "icon": "el-icon-picture",
                    "url": "instance_segmentation/image/",
                }
            ],
        },
        {
            "name": "�?题反�?",
            "icon": "fa-solid fa-comments",
            "models": [
                {
                    "name": "反�?�意�?",
                    "icon": "fa-regular fa-comment-dots",
                    "url": "feedback/feedback/",
                }
            ],
        },
        {
            "name": "历史记录管理",
            "icon": "fa-solid fa-clock-rotate-left",
            "models": [
                {
                    "name": "操作记录",
                    "icon": "fa-regular fa-calendar",
                    "url": "history/record/",
                }
            ],
        },
        {
            # 系统�?带模�?
            "app": "auth",
            "name": "用户管理",
            "icon": "fas fa-user-shield",
            "models": [
                {"name": "用户", "icon": "fa-solid fa-user", "url": "auth/user/"},
                {"name": "�?", "icon": "fa-solid fa-user-group", "url": "auth/group/"},
            ],
        },
    ],
}
# 图标设置
# 设置系统app的默认图标，不�?�求与SIMPLEUI_CONFIG�?保持一�?
SIMPLEUI_ICON = {
    "图像实例分割": "fa-regular fa-circle-nodes",
    "奶山羊图�?": "el-icon-picture",
    "�?题反�?": "fa-solid fa-comments",
    "反�?�意�?": "fa-regular fa-comment-dots",
    "历史记录管理": "fa-solid fa-clock-rotate-left",
    "操作记录": "fa-regular fa-calendar",
}

# 媒体设置
# 设置媒体�?�?
MEDIA_ROOT = BASE_DIR / "media"
# 设置媒体前缀
MEDIA_URL = "/media/"

# 临时文件存储�?�?
FILE_UPLOAD_TEMP_DIR = BASE_DIR / "temp"
