# Generated by Django 4.1.7 on 2023-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="反馈意见")),
                ("content", models.TextField(verbose_name="具体描述")),
                (
                    "feedback_type",
                    models.IntegerField(
                        choices=[(0, "使用问题"), (1, "改进建议")],
                        default=0,
                        verbose_name="反馈意见类型",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "反馈意见",
                "verbose_name_plural": "反馈意见",
            },
        ),
    ]
