# Generated by Django 4.1.7 on 2023-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/src/",
                        verbose_name="原始图像",
                    ),
                ),
                (
                    "out",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/out/",
                        verbose_name="分割结果",
                    ),
                ),
            ],
        ),
    ]
