# Generated by Django 4.1.7 on 2023-04-30 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("instance_segmentation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "奶山羊图像", "verbose_name_plural": "奶山羊图像"},
        ),
        migrations.AddField(
            model_name="image",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="mask",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="images/mask/",
                verbose_name="掩码图像",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
